config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'

  # Pages
  get "home", to: "pages#home"

  # Sessions
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"


  # Users
  get "signup", to: "users#new"
  resources :users, only: [:create, :edit, :update]

  # Messages
  post "message", to: "messages#create"

  # Channel
  mount ActionCable.server, at: '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, length: { minimum: 1, maximum: 200 }

  belongs_to :user

  scope :last_twenty_msgs, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 50 }

  has_many :messages, dependent: :destroy

  before_save :username_lowercase

  # username_lowercase
  def username_lowercase
    self.username = username.downcase
  end

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  helper_method :current_user, :logged_in?
  # current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # logged_in?
  def logged_in?
    !!current_user
  end

  # require_user
  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to view this page'
      redirect_to(login_path)
    end
  end

  # already_singed_up
  def already_singed_up
    if logged_in?
      flash[:alert] = 'You have already signed up'
      redirect_to(root_path)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  # post -> Create
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast('marce_room_channel', { messageHtml: message_render(message) })
    else
      flash.now[:alert] = 'There was a problem, please try again later'
    end
  end

  private

  # message params
  def message_params
    params.require(:message).permit(:body)
  end

  # message_render
  def message_render(message)
    render(partial: 'message', locals: { message: })
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Get -> Home
  def home
    @messages = Message.last_twenty_msgs
    @message = Message.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_singed_up, only: %i[new create]

  # get -> new
  def new; end

  # get -> create
  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to(root_path)
    else
      flash.now[:alert] = 'Incorrect credentials'
      render(:new, status: :unprocessable_entity)
    end
  end

  # delete -> destroy
  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]
  before_action :already_singed_up, only: %i[new create]
  before_action :require_same_user, only: %i[edit update]

  # New
  def new
    @user = User.new
  end

  # Get -> Edit
  def edit; end

  # Post -> Create
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New user #{@user.username} has been created"
      redirect_to(root_path)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  # Put -> Update
  def update
    if @user.update(user_params)
      flash[:notice] = "User #{@user.username} has been updated"
      redirect_to(root_path)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  private

  # get @user
  def set_user
    @user = User.find(params[:id])
  end

  # user params
  def user_params
    params.require(:user).permit(:username, :password)
  end

  # require_same_user
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit your own user'
      redirect_to(root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  # check character
  def check_character(character)
    characters = %w[
      ryu
      ken
      honda
      sagat
      cammy
      chun-li
      bison
      vega
      guile
      zangief
      balrog
      blanka
      deejay
      dhalsim
      feilong
      thawk
    ]
    characters.include?(character)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Chat</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
    <script>
      $(document).ready(function () {
        $(".ui.dropdown").dropdown()
      })
    </script>
  </head>
  <header>
    <%= render 'shared/navbar' %>
  </header>

  <body>
    <%= render 'shared/messages' %>
    <div class="ui container"><%= yield %></div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-container">
  <img
    src="<%=
  if check_character(message.user.username)
    "/images/#{message.user.username}.gif"
  else
    "https://ui-avatars.com/api/?name=#{message.user.username}&background=0D8ABC&color=fff"
  end
%>"
    width="100px"
    class="custom-avatar"
  />
  <p class="username-chat"><%= message.user.username.capitalize %><%= ' (admin) ' if message.user.admin? %>:</p>
  <p><%= message.body %></p>
</div>

app/views/pages/home.html.erb
<section>
  <h2 class="ui center aligned icon header">
    <i class="circular orange comments outline icon"></i>
    Let's Chat...
  </h2>

  <div class="ui two column grid">
    <div class="twelve wide column">
      <div class="ui fluid raised card">
        <div id="chatBox" class="chat-box">
          <%= render @messages %>
        </div>

        <div class="extra content">
          <%= form_for(@message,  html: { class: "ui reply form", role: "form" } , url: message_path, remote: true) do |f| %>
            <div class="field">
              <div class="ui fluid icon input">
                <%=
                  f.text_field :body,
                               placeholder: 'Enter a message...',
                               required: true,
                               class: 'ui fluid icon input',
                               id: 'messageBody'
                %>
                <%= f.button '<i class="bordered inverted orange icon edit"></i>'.html_safe, id: 'chatBtn' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="four wide column">
      <div class="ui vertical inverted menu">
        <%= link_to 'Home', root_path, class: 'active item' %>
      </div>
    </div>
  </div>

  <script>
    // Get the container element
    var container = document.getElementById("chatBox")

    // Scroll to the bottom
    container.scrollTop = container.scrollHeight
  </script>
</section>

app/views/shared/_errors.html.erb
<% if obj.errors.any?  %>
  <div class="ui icon message">
    <i class="red exclamation icon"></i>
    <div class="content">
      <p class="header">The following errors prevented the new <%= obj.class %> being created:</p>
      <ul class="">
        <% obj.errors.full_messages.each do |message|  %>
          <li><%= message %></li>
        <% end  %>
      </ul>
    </div>
  </div>
<% end  %>

app/views/shared/_messages.html.erb
<%  flash.each do |key,value|%>
  <div class="ui container margin-y-20">
    <div class="ui icon message">
      <i class="<%= key == 'notice' ? 'green thumbs up outline' : 'red exclamation' %> icon"></i>
      <p><%= value %></p>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to 'Rails Chat', root_path, class: 'item title' %>
    <div class="right menu">
      <% unless logged_in? %>
        <div class="item">
          <div class="ui buttons">
            <%= link_to signup_path do %>
              <button class="ui inverted orange button">Sign up</button>
            <% end %>

            <div class="or"></div>
            <%= link_to login_path do %>
              <button class="ui orange button">Log in</button>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="user-container item">
          <%= link_to current_user.username.capitalize, edit_user_path(current_user), class: 'ui inverted username' %>
          <%= link_to logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
            <div class="item">
              <div class="ui inverted red button">Log out</div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, url: action_path, method: method, class: "ui form") do |f| %>
  <div class="field">
    <%= f.text_field :username, placeholder: 'Username', required: true %>
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder: 'Password', required: true %>
  </div>

  <%= f.submit(@user.new_record? ? 'Sign up' : 'Update Account', class: 'ui orange inverted button') %>
<% end %>

app/views/users/edit.html.erb
<section>
  <h2 class="ui center aligned icon header">
    <i class="circular orange edit outline icon"></i>
  </h2>
  <%= render 'form', action_path: user_path, method: :put %>
</section>

app/views/users/new.html.erb
<section>
  <h2 class="ui center aligned icon header">
    <i class="circular orange user plus icon"></i>
  </h2>
  <%= render 'form', action_path: users_path, method: :post %>
</section>